# Generated by Django 6.0.6 on 2026-07-22 13:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCapacityLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DemoThrottleBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('workspace_start', 'Workspace start')], max_length=32)),
                ('window_started_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key_hash', 'action'), name='vanta_demo_unique_throttle_bucket')],
            },
        ),
        migrations.CreateModel(
            name='DemoWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('browser_id', models.UUIDField()),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('active', 'Active'), ('expired', 'Expired'), ('failed', 'Failed'), ('retired', 'Retired')], default='creating', max_length=16)),
                ('seed_version', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='vanta_demo_status_expiry_idx'), models.Index(fields=['browser_id', 'status'], name='vanta_demo_browser_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['creating', 'active'])), fields=('browser_id',), name='vanta_demo_one_live_workspace_per_browser')],
            },
        ),
    ]
