# Generated by Django 6.0.6 on 2026-07-22 13:48

from django.db import migrations


def create_capacity_lock(apps, schema_editor):
    capacity_lock = apps.get_model('vanta_demo', 'DemoCapacityLock')
    capacity_lock.objects.using(schema_editor.connection.alias).get_or_create(pk=1)


def remove_capacity_lock(apps, schema_editor):
    capacity_lock = apps.get_model('vanta_demo', 'DemoCapacityLock')
    capacity_lock.objects.using(schema_editor.connection.alias).filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vanta_demo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_capacity_lock, remove_capacity_lock),
    ]
