# Generated by Django 6.0.6 on 2026-07-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('canonical_site_slug', models.CharField(blank=True, max_length=40)),
                ('cover_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', 'published_at'], name='demo_conten_is_publ_fc48b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('repo_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['is_published', 'is_featured', 'sort_order'], name='demo_conten_is_publ_0dc71a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPostPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_slug', models.CharField(max_length=40)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='demo_content.blogpost')),
            ],
            options={
                'ordering': ['site_slug'],
                'indexes': [models.Index(fields=['site_slug'], name='demo_conten_site_sl_988833_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'site_slug'), name='demo_blog_one_publication_per_site')],
            },
        ),
        migrations.CreateModel(
            name='BlogPostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('excerpt', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='demo_content.blogpost')),
            ],
            options={
                'ordering': ['language_code', 'title'],
                'indexes': [models.Index(fields=['language_code', 'slug'], name='demo_conten_languag_bec425_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'language_code'), name='demo_blog_one_translation_per_language'), models.UniqueConstraint(fields=('language_code', 'slug'), name='demo_blog_unique_slug_per_language')],
            },
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('summary', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='demo_content.project')),
            ],
            options={
                'ordering': ['language_code', 'title'],
                'indexes': [models.Index(fields=['language_code', 'slug'], name='demo_conten_languag_24b806_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'language_code'), name='demo_projects_one_translation_per_language'), models.UniqueConstraint(fields=('language_code', 'slug'), name='demo_projects_unique_slug_per_language')],
            },
        ),
    ]
